name: flutter_weather_app
publish_to: "none"
version: 1.0.0+136

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  share_plus: ^3.1.0
  connectivity_plus: ^2.2.1
  yaml: ^3.1.0 

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # architecture
  data:
    path: modules/architecture/data
  domain:
    path: packages/domain
  ui:
    path: modules/architecture/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.13.0

flutter:
  uses-material-design: true
  generate: true # used for localizations

  assets:
    - pubspec.yaml # used for displaying app version from this file
    - assets/icons/weather/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
