name: flutter_weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  get: ^4.6.1
  share_plus: ^3.1.0
  geolocator: ^8.2.0
  connectivity_plus: ^2.2.1

  data:
    path: packages/data/

  domain:
    path: packages/domain/  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
  - assets/icons/
