name: flutter_weather_app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  get: ^4.6.1

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # architecture
  data:
    path: packages/data/
  domain:
    path: packages/domain/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.11.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
  