name: flutter_weather_app
publish_to: "none"
version: 1.0.0+118

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  get: ^4.6.1
  dartz: ^0.10.1
  share_plus: ^3.1.0
  connectivity_plus: ^2.2.1
  flutter_svg: ^1.0.3
  yaml: ^3.1.0 

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  data:
    path: packages/data/
  domain:
    path: packages/domain/
  weather_ui:
    path: packages/weather_ui/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.12.0

flutter:
  uses-material-design: true
  generate: true # used for localizations

  assets:
    - pubspec.yaml
