name: ui
publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.4"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.13.0

flutter:
  uses-material-design: true
