name: domain

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8     
  mockito: ^5.1.0  
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.13.0
